### PR TITLE
Build with the limited ABI

### PR DESCRIPTION
**Pull request by rdb**
Thank you for this project!
I hope you don't mind that I built wheels for pyTinySoundFont and uploaded them to PyPI, so that it is easier to use this project by installing via `pip`: https://pypi.org/project/pyTinySoundFont/
Of course, I can add you as a owner if you provide me with your username, since this is your project after all.

Anyway, in order to create wheels that are compatible with multiple Python versions, I used the changes in this PR to indicate that it uses the "limited ABI". This brings this repository in line with what is uploaded to PyPI.

### CODE REVIEW

**Comment by fynv** [comment]
Hi, thanks for your interest in the project.
This was written as a side-project of https://github.com/fynv/ScoreDraft.
Now both of the two projects are not being actively maintained.

I've just taken a quick look of what I did, and found that now I actually have some better idea of what to do with this kind of projects. To be "compatible with multiple Python versions", I would rather use cffi(ABI) now. 

Just give me some time, I will do an update to this project.

**Comment by fynv** [comment]
Switched to cffi for C bindings.
With CFFI, we simply include all the binary modules into a single wheel. 
The attached wheel contains a .dll for Windows 64bit and a .so for Linux 64bit.

[pyTinySoundFont-0.1.0-py3-none-any.whl.zip](https://github.com/fynv/pyTinySoundFont/files/9740869/pyTinySoundFont-0.1.0-py3-none-any.whl.zip)

Note that the binary modules built this way is independent to Python versions.
But they might be dependent to the ABI of the OS runtime. Test needed.

**Comment by janEntikan** [comment]
I would also like a .so for Linux ARM64/aarch64 (so I can compose on my pinephone), which are currently wheels on pypi thanks to @rdb. I don't like the idea of calling it "py3-none-any" when it only supports two architectures.

**Comment by janEntikan** [comment]
Also, there are currently macos wheels on pypi which is pretty cool too. Are you sure having a limited set of binary modules is the right approach?

**Comment by rdb** [comment]
Using cffi instead of the native CPython API is fine if that's what you prefer, but I don't think we can get away from platform-specific wheels, there are too many platforms to cover and putting all those in a single wheel that pretends to be platform-independent doesn't seem like a good idea (at the very least such a wheel should be tagged with all the supported platforms with a long dot-separated platform tag).

Also, I think it's a downgrade that the C extension is no longer built by setup.py, since installing from sdist is now impossible.

For Linux the wheels should be built in a manylinux docker container. Also see cibuildwheel which can be used in a GitHub Actions builder to automate this. But I'm used to building wheels for other projects so I'd be happy to build them for you.

**Comment by fynv** [comment]
Ok @rdb.  Basically you can just go ahead with the Python-extension build in your fork and release to PyPi etc.
There's no more updates planned in this repo, so no need to worry about conflicts.

Using cffi is kind of a opportunistic approach to mitigate the package maintainence burden, which is an inherent drawback of Python. I don't think there's any perfect solution yet.
I found cffi to be good enough for most cases(maybe not this one) and have been using it in most of my more recent projects. 

Package naming seems to be the main problem here. Frankly I've no idea what they should better be called. 

Given that the binary libs are quite small, it is actually possible to put a lot of them into the wheel, but I agree that it doesn't look like a good idea.

**Comment by fynv** [comment]
Just a little off-topic: I found this might be a case where WASM can be a better solution, but this is not Node.js.. sad.

**Comment by fynv** [comment]
Closing not merging. @rdb you have my permission to do what you want. I will add an announcement to go "https://github.com/rdb/pytinysoundfont" in my readme if you would like. Thanks.

**Comment by rdb** [comment]
OK, thanks!

**Comment by fynv** [comment]
In case you are interested, I've just done a WASM(wasmer_python) based implementation:

[https://github.com/fynv/pyTinySoundFont/tree/master/wasm](https://github.com/fynv/pyTinySoundFont/tree/master/wasm)

Poor performance + other problems such as 16MB limited memory by default.

Just interesting to try anyway.

**Comment by fynv** [comment]
Got a quite efficient WASM implementation just now, by replacing wasmer with wasmtime.

Overwriting: 

https://github.com/fynv/pyTinySoundFont/tree/master/wasm

Made a PyPi release to:

https://pypi.org/project/pyTinySoundFontWASM

Should work as long as wasmtime is available.

**Comment by rdb** [comment]
Wow, interesting. I was not aware of the existence of wasmtime so I hadn't considered this as an option.

**Pull request closed without merging**
